brlcad: add missing nlohmann_json
fix for strictDeps:

```cpp
In file included from /build/source/src/libged/bot/dump/gltf.cpp:35:
/nix/store/1x7kx0nia54542fsic0a0fk999qnm595-tinygltf-2.9.7/include/tiny_gltf.h:1715:10: fatal error: json.hpp: No such file or directory
 1715 | #include "json.hpp"
      |          ^~~~~~~~~~
```